import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { renderSelfSkill } from '../src/skill.mjs';

const home = mkdtempSync(join(tmpdir(), 'declick-cmd-'));
const skills = mkdtempSync(join(tmpdir(), 'skills-cmd-'));
const env = { ...process.env, DECLICK_HOME: home, DECLICK_SKILLS: skills, OPENCLAW_SKILLS: '', CREDS_VAULT: join(home, 'none.env'), DASHCLAW_API_KEY: '', DASHCLAW_URL: '', DECLICK_GUARD: '', DECLICK_DESK: join(home, 'no-desk') };
const run = (args, extra = {}) => spawnSync(process.execPath, ['bin/declick.mjs', ...args], { env: { ...env, ...extra }, encoding: 'utf8', timeout: 30000 });
const J = r => { try { return JSON.parse(r.stdout); } catch { throw new Error(`not json (exit ${r.status}): ${r.stdout}\n${r.stderr}`); } };
const VERSION = JSON.parse(readFileSync('package.json', 'utf8')).version;
const rows = J(run(['commands', '--limit', '100'])).data;

test('commands is the whole command surface as data', () => {
  assert.ok(rows.length >= 25, `only ${rows.length} commands`);
  for (const name of ['add', 'run', 'author', 'repair', 'accept', 'build', 'describe', 'manifest', 'lint', 'list', 'status', 'doctor', 'auth', 'engines', 'path', 'setup', 'uninstall', 'proposals', 'recipes', 'recipe', 'skill', 'remove', 'export', 'import', 'desk', 'ui', 'audit', 'commands', 'version', 'help'])
    assert.ok(rows.find(c => c.name === name), `no row for ${name}`);
  for (const c of rows) {
    assert.match(c.usage, new RegExp(`^declick ${c.name}\\b`), c.name);
    assert.ok(c.summary && c.summary.length <= 90, `${c.name}: ${c.summary}`);
    assert.ok(Array.isArray(c.positionals) && Array.isArray(c.flags) && Array.isArray(c.examples), c.name);
    assert.equal(typeof c.mutating, 'boolean'); assert.equal(typeof c.dryRun, 'boolean');
  }
  assert.deepEqual(J(run(['commands', '--fields', 'name', '--limit', '2'])).data.map(r => Object.keys(r)), [['name'], ['name']]);
  assert.equal(J(run(['commands', '--limit', '2'])).meta.count, rows.length);
});
test('describe declick is the same table', () => {
  const d = J(run(['describe', 'declick']));
  assert.equal(d.ok, true);
  assert.deepEqual(d.data.map(c => c.name), rows.map(c => c.name));
});
test('every command answers --help with its own row and exit 0', () => {
  for (const c of rows) {
    const r = run([c.name, '--help']);
    assert.equal(r.status, 0, `${c.name}: exit ${r.status} ${r.stdout}${r.stderr}`);
    assert.equal(J(r).data.name, c.name);
  }
  for (const name of ['add', 'ui', 'run', 'audit']) {
    const c = rows.find(x => x.name === name);
    const t = run([name, '--help', '--json', 'false']);
    assert.equal(t.status, 0, `${name}: ${t.stderr}`);
    assert.ok(t.stdout.startsWith(c.usage), `${name} help text: ${t.stdout.split('\n')[0]}`);
    assert.ok(t.stdout.includes(c.summary), name);
  }
  assert.equal(J(run(['help', 'describe'])).data.name, 'describe');
});
test('help --json is data, not a prose blob', () => {
  const h = J(run(['help']));
  assert.equal(h.data.version, VERSION);
  assert.deepEqual(h.data.commands.map(c => c.name), rows.map(c => c.name));
  for (const c of rows) assert.match(h.data.usage, new RegExp(`\\n  declick ${c.name}\\b`), c.name);
});
test('the shipped declick skill is rendered from the table', () => {
  const shipped = readFileSync('skills/declick/SKILL.md', 'utf8');
  assert.match(shipped, /Generated by declick/);
  for (const c of rows) assert.match(shipped, new RegExp(`\\bdeclick ${c.name}\\b`), `${c.name} is missing from skills/declick/SKILL.md`);
  assert.equal(shipped, renderSelfSkill(rows, VERSION), 'skills/declick/SKILL.md has drifted from the command table');
});
test('unknown command suggests the nearest ones and prints no usage blob', () => {
  const r = run(['lst']);
  assert.equal(r.status, 1);
  const e = J(r).error;
  assert.match(e, /unknown command lst/); assert.match(e, /did you mean .*\blist\b/); assert.match(e, /declick commands/);
  assert.ok(!e.includes('\n'), `usage blob in the error: ${e}`);
  assert.match(J(run(['zzzzzzzzzz'])).error, /^unknown command zzzzzzzzzz; run: declick commands$/);
});
test('an unknown flag names the raw token, what it ate, and the nearest flag', () => {
  const r = run(['add', 'fixtures/petstore.json', '--nmae', 'pets']);
  assert.equal(r.status, 1, r.stdout);
  const e = J(r).error;
  assert.match(e, /unknown flag --nmae for add/); assert.match(e, /consumed "pets"/); assert.match(e, /did you mean --name\?/); assert.match(e, /declick add --help/);
  assert.match(J(run(['list', '--verbose'])).error, /unknown flag --verbose for list/);
  assert.equal(run(['describe', 'ghost', '--full']).status, 2, 'a known flag still reaches the command');
});
test('a missing positional names the command row', () => {
  const r = run(['describe']);
  assert.equal(r.status, 1);
  const e = J(r).error;
  assert.match(e, /^usage: declick describe <name>/); assert.match(e, /declick describe --help/);
  assert.match(J(run(['recipe', 'x'])).error, /^usage: declick recipe <name> <verb>/);
  assert.equal(run(['status']).status, 0, 'an optional positional is still optional');
});
