import { existsSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, oneLine } from './describe.mjs';

const MARKER = 'Generated by declick';
const SELF = join(dirname(fileURLToPath(import.meta.url)), '..', 'skills', 'declick', 'SKILL.md');
const yamlStr = s => JSON.stringify(oneLine(s));
// Nothing embedded in a fenced block may close it, whatever the spec put in the manifest.
const fence = s => String(s).replace(/```/g, "'''");
const token = a => a.name.toUpperCase().replace(/[^A-Z0-9]+/g, '_');

export function skillDirs() {
  const dirs = [process.env.DECLICK_SKILLS || join(homedir(), '.claude', 'skills')];
  if (process.env.OPENCLAW_SKILLS) dirs.push(process.env.OPENCLAW_SKILLS);
  return dirs;
}

const marked = p => !existsSync(p) || readFileSync(p, 'utf8').includes(MARKER);

// The preflight callers run before they write anything else, so a refusal never leaves half an adapter.
export function canWriteSkill(name, { force = false } = {}) {
  const bad = force ? null : skillDirs().map(d => join(d, name, 'SKILL.md')).find(p => !marked(p));
  if (bad) throw Object.assign(new Error(`${bad} exists and was not written by declick; pick another --name or pass --force`), { exit: 1 });
  return true;
}

function write(name, body, dirs) {
  return dirs.map(d => {
    const dir = join(d, name); mkdirSync(dir, { recursive: true });
    const p = join(dir, 'SKILL.md');
    writeFileSync(p, body); return p;
  });
}

// What the first failure of this engine looks like and what it names, so nobody reaches for a screenshot.
function tail(m) {
  const auth = m.auth?.env?.length ? `, 4 auth needed (then: declick auth ${m.name}, or creds mint ${m.name})` : '';
  if (m.engine === 'desktop') return `Exit 2 means an element path or the window stopped resolving (then: declick repair ${m.name} <verb>). Exit 3 means deskclaw is not armed or STOP is set (then: declick desk arm 30). The "${oneLine(m.window, 500)}" window must be open on this desktop before any verb runs; verbs without --dry-run act on it.`;
  if (m.engine === 'web') return `Exit 2 means a selector stopped matching: the error carries data.candidates, the real elements on the page, so fix the recipe from that and never from a screenshot. Exit 1 with no browser means Chrome or Edge is missing (then: set CHROME=<path>). Verbs without --dry-run drive a real browser on ${oneLine(m.window, 500)}.`;
  if (m.engine === 'mcp') return `Exit 2 means the verb is not in the server tools list, 3 blocked by governance${auth}. Every verb starts ${oneLine(m.source, 200)}, calls one tool and exits, so the server does not have to be running first.`;
  if (m.engine === 'sqlite') return `Exit 2 means the row or the database file is not there, 1 is a constraint or a bad statement and carries the sqlite message. Every verb opens ${oneLine(m.baseUrl || m.source, 500)} directly; the file must exist and be writable for the mutating verbs.`;
  if (m.engine === 'cli') return `Exit 2 means the tool exited 2 or said not found, 1 is any other failure and data carries stdout, stderr and code. Every verb spawns ${oneLine(m.source, 200)}, which must be on PATH. A flag renamed --param-<name> collided with a contract flag.`;
  return `Exit 2 means not found, 3 blocked by governance${auth}.`;
}

// A required flag with no value is the most common first failure: spend the example the spec gave, or a token to replace.
const required = v => (v.flags || []).filter(f => f.required).map(f => ` --${oneLine(f.name, 100)} ${f.example === undefined ? token(f) : oneLine(String(f.example), 60)}`).join('');

export function writeSkill(m, opts) {
  const examples = m.verbs.slice(0, 3).map(v => `${m.name} ${v.name}${v.args.map(a => ` ${token(a)}`).join('')}${required(v)}${v.mutating ? ' --dry-run' : ''}`);
  const body = `---
name: ${m.name}
description: ${yamlStr(`Use when you need to ${m.verbs[0].description.toLowerCase()} or other ${m.name} operations from the shell. Run '${m.name} describe' first.`)}
---

# ${m.name}

${MARKER} from ${oneLine(m.source, 500)}. Deterministic, no screenshots, JSON by default when piped.

\`\`\`
${fence(describe(m))}
\`\`\`

Examples (replace UPPERCASE tokens with real values; 'declick describe ${m.name} --verb <verb>' prints one verb's flags and what it returns):

\`\`\`
${fence(examples.join('\n'))}
\`\`\`

If '${m.name}' is not on PATH, run every command as: declick run ${m.name} <verb> ... (same output, same exit codes).
Every verb: --json (default when piped) --fields a,b --limit N; mutating verbs accept --dry-run. Success: {"ok":true,"data":...,"meta":{"count":N,"truncated":false}}. Failure: {"ok":false,"error":"...","exit":N}.
${tail(m)}
`;
  canWriteSkill(m.name, opts);
  return write(m.name, body, skillDirs());
}

// declick's own skill is rendered from the command table, so it can never drift from what the CLI accepts.
export function renderSelfSkill(commands, version) {
  const w = Math.min(Math.max(...commands.map(c => c.usage.length)), 68);
  const rows = commands.map(c => `${c.usage.padEnd(w)}  ${c.summary}`);
  const previews = commands.filter(c => c.dryRun).map(c => c.name);
  return `---
name: declick
description: "Use when you need to turn an OpenAPI spec, an MCP server or a native app into a CLI, or to run, inspect, repair or remove an adapter declick already built. Every action is one declick command with --json output; never edit ~/.declick by hand."
---

# declick

${MARKER} ${version}. Turns anything into a CLI so agents stop clicking: no screenshots, no DOM dumps. Every command returns \`{"ok":true,"data":...,"meta":{"count":N,"truncated":false}}\` on success and \`{"ok":false,"error":"...","exit":N}\` on failure (JSON is the default when piped; add \`--json\` to force it). Exit codes: 0 ok, 1 error, 2 not found, 3 blocked by governance or an unarmed desktop, 4 auth needed.

Start with \`declick doctor\`, then \`declick list\`, then \`declick describe <name> --full\`.

\`\`\`
${fence(rows.join('\n'))}
\`\`\`

\`declick <command> --help\` prints one row (flags, examples, whether it previews) and \`declick commands\` is this table as data, so nothing here has to be memorized.

Flags every generated verb accepts: \`--json\`, \`--fields a,b\` (dotted paths ok), \`--limit N\`, \`--rows path\` (unwrap a nested array; auto-applied when the verb's \`returns.rowsPath\` is known and \`--fields\`/\`--limit\` is passed), \`--dry-run\` (mutating verbs), \`--help\`. Both \`--flag value\` and \`--flag=value\` work; boolean flags never eat the next argument. Unknown flags are an error, not ignored. Management commands that preview with \`--dry-run\`: ${previews.join(', ')}. \`describe --full\` shows each verb's flags, auth and compiled \`returns\`.
`;
}

// declick's own skill, so an agent that finds one adapter learns how to make the next.
// Only dirs where the file is absent or already carries the marker are written: a hand-written declick skill stays.
export function writeSelfSkill(commands, version) {
  const body = commands ? renderSelfSkill(commands, version) : existsSync(SELF) ? readFileSync(SELF, 'utf8') : null;
  if (body === null) return [];
  return write('declick', body, skillDirs().filter(d => marked(join(d, 'declick', 'SKILL.md'))));
}

export function removeSkill(name) {
  return skillDirs().map(d => join(d, name)).filter(p => {
    const f = join(p, 'SKILL.md');
    if (!existsSync(f) || !readFileSync(f, 'utf8').includes(MARKER)) return false;
    rmSync(p, { recursive: true, force: true }); return true;
  });
}
