import { mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { describe } from './describe.mjs';

export function skillDirs() {
  const dirs = [process.env.DECLICK_SKILLS || join(homedir(), '.claude', 'skills')];
  if (process.env.OPENCLAW_SKILLS) dirs.push(process.env.OPENCLAW_SKILLS);
  return dirs;
}

export function writeSkill(m) {
  const examples = m.verbs.slice(0, 3).map(v => `${m.name} ${v.name}${v.args.map(a => ` <${a.name}>`).join('')}${v.mutating ? ' --dry-run' : ''}`);
  const body = `---
name: ${m.name}
description: Use when you need to ${m.verbs[0].description.toLowerCase()} or other ${m.name} operations from the shell. Run '${m.name} describe' first.
---

# ${m.name}

Generated by declick from ${m.source}. Deterministic, no screenshots, JSON by default when piped.

\`\`\`
${describe(m)}
\`\`\`

Examples:

\`\`\`
${examples.join('\n')}
\`\`\`

Mutating verbs accept --dry-run. Exit 2 means not found, 3 blocked, 4 auth needed (then: creds mint ${m.name}).
`;
  return skillDirs().map(d => { const dir = join(d, m.name); mkdirSync(dir, { recursive: true }); const p = join(dir, 'SKILL.md'); writeFileSync(p, body); return p; });
}
