import { existsSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe } from './describe.mjs';

const MARKER = 'Generated by declick';
const SELF = join(dirname(fileURLToPath(import.meta.url)), '..', 'skills', 'declick', 'SKILL.md');
// Spec text is untrusted: one line, no backticks, no YAML breakouts, bounded length.
const oneLine = (s, n = 200) => String(s).replace(/[\r\n]+/g, ' ').replace(/`/g, "'").trim().slice(0, n);
const yamlStr = s => JSON.stringify(oneLine(s));
const token = a => a.name.toUpperCase().replace(/[^A-Z0-9]+/g, '_');

export function skillDirs() {
  const dirs = [process.env.DECLICK_SKILLS || join(homedir(), '.claude', 'skills')];
  if (process.env.OPENCLAW_SKILLS) dirs.push(process.env.OPENCLAW_SKILLS);
  return dirs;
}

function write(name, body, { force = false } = {}) {
  return skillDirs().map(d => {
    const dir = join(d, name); mkdirSync(dir, { recursive: true });
    const p = join(dir, 'SKILL.md');
    if (existsSync(p) && !force && !readFileSync(p, 'utf8').includes(MARKER)) {
      throw Object.assign(new Error(`${p} exists and was not written by declick; pick another --name or pass --force`), { exit: 1 });
    }
    writeFileSync(p, body); return p;
  });
}

function tail(m) {
  if (m.engine === 'desktop') return `Exit 2 means an element path or the window stopped resolving (then: declick repair ${m.name} <verb>). Exit 3 means deskclaw is not armed or STOP is set (then: declick desk arm 15). Verbs without --dry-run act on the live "${oneLine(m.window)}" window.`;
  return `Exit 2 means not found, 3 blocked by governance${m.auth?.env?.length ? `, 4 auth needed (then: declick auth ${m.name}, or creds mint ${m.name})` : ''}.`;
}

export function writeSkill(m, opts) {
  const examples = m.verbs.slice(0, 3).map(v => `${m.name} ${v.name}${v.args.map(a => ` ${token(a)}`).join('')}${v.mutating ? ' --dry-run' : ''}`);
  const body = `---
name: ${m.name}
description: ${yamlStr(`Use when you need to ${m.verbs[0].description.toLowerCase()} or other ${m.name} operations from the shell. Run '${m.name} describe' first.`)}
---

# ${m.name}

${MARKER} from ${oneLine(m.source)}. Deterministic, no screenshots, JSON by default when piped.

\`\`\`
${describe(m)}
\`\`\`

Examples (replace UPPERCASE tokens with real values; '${m.name} describe --full' lists per-verb flags):

\`\`\`
${examples.join('\n')}
\`\`\`

If '${m.name}' is not on PATH, run every command as: declick run ${m.name} <verb> ... (same output, same exit codes).
Every verb: --json (default when piped) --fields a,b --limit N; mutating verbs accept --dry-run. Success: {"ok":true,"data":...,"meta":{"count":N,"truncated":false}}. Failure: {"ok":false,"error":"...","exit":N}.
${tail(m)}
`;
  return write(m.name, body, opts);
}

// declick's own skill, so an agent that finds one adapter learns how to make the next.
export function writeSelfSkill() {
  if (!existsSync(SELF)) return [];
  return write('declick', readFileSync(SELF, 'utf8'), { force: true });
}

export function removeSkill(name) {
  return skillDirs().map(d => join(d, name)).filter(p => {
    const f = join(p, 'SKILL.md');
    if (!existsSync(f) || !readFileSync(f, 'utf8').includes(MARKER)) return false;
    rmSync(p, { recursive: true, force: true }); return true;
  });
}
